// Generated by CoffeeScript 1.12.4
var Rejected, cast;

Rejected = require('../utils').Rejected;

cast = require('./cast');

module.exports = {
  assign: function(model, relation, obj, options) {
    var e, foreignKey, related;
    if (relation.options.through) {
      return Rejected(new Error("Can't assign relation with interim model"));
    }
    foreignKey = this.relatedData.key('foreignKey');
    try {
      related = cast.saveOrFetch(this, obj, options, "Can't assign " + obj + " to " + model + " as a " + relation.name);
      return related.then(function(related) {
        return model.save(foreignKey, related.id, options);
      });
    } catch (error) {
      e = error;
      return Rejected(e);
    }
  }
};
