// Generated by CoffeeScript 1.12.4
var Fulfilled, Rejected, ref;

ref = require('../utils'), Rejected = ref.Rejected, Fulfilled = ref.Fulfilled;

module.exports = {
  forgeOrFetch: function(self, obj, options, msg) {
    var model;
    model = self.model || self.constructor;
    switch (false) {
      case obj !== null:
        return Fulfilled(null);
      case typeof obj !== 'number':
        return model.forge({
          id: obj
        }).fetch(options);
      case obj.constructor !== Object:
        return Fulfilled(model.forge(obj));
      case !(obj instanceof model):
        return Fulfilled(obj);
      default:
        throw new Error(msg);
    }
  },
  saveOrFetch: function(self, obj, options, msg) {
    var model;
    model = self.model || self.constructor;
    switch (false) {
      case obj !== null:
        return Fulfilled({
          id: null
        });
      case typeof obj !== 'number':
        return model.forge({
          id: obj
        }).fetch(options);
      case obj.constructor !== Object:
        return model.forge(obj).save(null, options);
      case !(obj instanceof model):
        return Fulfilled(obj);
      default:
        throw new Error(msg);
    }
  }
};
