// Generated by CoffeeScript 1.12.4
var assign, attach, detach, ref;

ref = require('./has_many'), assign = ref.assign, attach = ref.attach, detach = ref.detach;

module.exports = {
  assign: assign,
  attach: attach,
  _attachOne: function(model, relation, obj, options) {
    obj.set(this.relatedData.key('foreignKey'), model.id);
    obj.set(this.relatedData.key('morphKey'), this.relatedData.key('morphValue'));
    return obj.save(null, options);
  },
  detach: detach,
  _detachOne: function(model, relation, obj, options) {
    obj.set(this.relatedData.key('foreignKey'), null);
    obj.set(this.relatedData.key('morphKey'), null);
    return obj.save(null, options);
  }
};
