// Generated by CoffeeScript 1.12.4
module.exports = {
  assign: function(model, relation, obj, morphValue, options) {
    var foreignKey, morphKey;
    if (typeof morphValue !== 'string') {
      options = morphValue;
      morphValue = obj != null ? obj.tableName : void 0;
    }
    foreignKey = this.relatedData.key('foreignKey');
    morphKey = this.relatedData.key('morphKey');
    model.set(foreignKey, obj != null ? obj.id : void 0);
    model.set(morphKey, morphValue);
    return model.save(null, options);
  }
};
